### ISSUE TITLE
Erro in file web.py

### ISSUE THREAD

**Issue by migo1271** [lavolp3/spotify-ripper#10]
Unfortunately, installing and running spotify-ripper causes the folling error:
Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 11, in <module>
    load_entry_point('spotify-ripper==2.9.1', 'console_scripts', 'spotify-ripper')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/bin/main.py", line 4, in <module>
    __import__('pkg_resources').run_script('spotify-ripper==2.9.1', 'main.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper-2.9.1-py2.7.egg/EGG-INFO/scripts/main.py", line 7, in <module>
    from spotify_ripper.ripper import Ripper
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper-2.9.1-py2.7.egg/spotify_ripper/ripper.py", line 11, in <module>
    from spotify_ripper.web import *
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper-2.9.1-py2.7.egg/spotify_ripper/web.py", line 368
    
    ^
SyntaxError: EOF while scanning triple-quoted string literal

**Comment by lavolp3** [comment]
I've seen the issue.
Will repair later today.

**Comment by lavolp3** [comment]
There was a scripting error, I left part of a comment in the code.
Should be solved now. Do a git pull and don't forget to install the scripts again via setup.py.
Please let me know if it works.

**Comment by migo1271** [comment]
Thank you ver much. It is working now :)

**Comment by lavolp3** [comment]
Very good.
Please note that cover download is broken at the moment and some other things need to be fixed. But the basic download should work.
Closing this now
