### ISSUE TITLE
No module named spotipy.util

### ISSUE THREAD

**Issue by ramonskie** [lavolp3/spotify-ripper#6]
when running any `spotify-ripper` commands
i get the following error
it seems that the library is missing.

```
Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 11, in <module>
    load_entry_point('spotify-ripper==2.9.1', 'console_scripts', 'spotify-ripper')()
  File "/home/ramonskie/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ramonskie/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/home/ramonskie/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/home/ramonskie/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/bin/main.py", line 4, in <module>
    __import__('pkg_resources').run_script('spotify-ripper==2.9.1', 'main.py')
  File "/home/ramonskie/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/ramonskie/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1437, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper-2.9.1-py2.7.egg/EGG-INFO/scripts/main.py", line 7, in <module>
    from spotify_ripper.ripper import Ripper
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper-2.9.1-py2.7.egg/spotify_ripper/ripper.py", line 15, in <module>
    from spotify_ripper.spotipy_integration import get_playlist_tracks, init_spotipy
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper-2.9.1-py2.7.egg/spotify_ripper/spotipy_integration.py", line 3, in <module>
    import spotipy.util as util
ImportError: No module named spotipy.util
```

**Comment by ramonskie** [comment]
i tried `pip install spotipy`

**Comment by ramonskie** [comment]
when adding spotipy to the requirments section here
https://github.com/lavolp3/spotify-ripper/blob/master/setup.py#L47

it works.
i first thougt requirement.txt was used for this.

**Comment by lavolp3** [comment]
Thanks for noticing!
Missed that while integrating the Web API for playlist scraping functions.

**Comment by lavolp3** [comment]
Have amended setup.py as suggested.
If you have some time can you test it by reinstalling?

requirements.txt seems to be an unnecessary artifact. Will check this out if I have time.

**Comment by ramonskie** [comment]
cleaned my python env and rerun the scripts. seems to work so far
